
name: Proyecto prueba

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: 
      - qa
      - uat
      - main
    types: 
      - closed

jobs:

  build:
    runs-on: self-hosted-qa  

    env:
      WORKING_DIRECTORY: VentaDigitalPQF
      IIS_SITE_NAME: "VentaDigitalDevops"
      IS_SITE_PATH: "C:\\Sitios\\VentaDigitalDevops"              

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "VentaDigitalPQF" --configuration Release --output ./myapp

    - name: dotnet publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration Release --output ./myapp
      
       
