
name: Pruebas SAP

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: 
      - qa
      - uat
      - main
    types: 
      - closed

env:
      WORKING_DIRECTORY: VentaDigitalPQF
      IIS_SITE_NAME: "VentaDigitalDevops"
      IIS_POOL_NAME: "AppCoreDevops"
      IS_SITE_PATH: "C:\\Sitios\\VentaDigitalDevops"

jobs:

  build:
    runs-on: self-hosted-qa  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
